/**
 * Static reference data pulled from the club's public tracker page
 * (cobegbd.com) — content that doesn't fit the existing Prisma schema and
 * isn't something an admin edits day-to-day (a historical transfer log, a
 * point-in-time ranking snapshot), so it lives here as plain data instead of
 * needing a database migration.
 *
 * THIS FILE IS AUTO-GENERATED by prisma/sync-from-tracker.ts (sync-with-
 * tracker.bat). Manual edits here will be overwritten on the next sync —
 * change the tracker data instead, or edit sync-from-tracker.ts if the
 * formatting itself needs to change.
 *
 * Last synced: 2026-09-11T09:04:31.595Z
 */

export type TransferEvent = {
  date: string; // ISO date, tracker's own listed date
  type: 'NEW_REGISTER' | 'TRANSFER' | 'UNREGISTER';
  player: string;
  squad: string; // e.g. "Main #13"
  fromClub?: string; // only set when the tracker names a previous club
};

// Straight from the tracker's Transfers tab (newest first, as published).
export const TRANSFERS: TransferEvent[] = [
  { date: "2026-09-09", type: "TRANSFER", player: "apba371", squad: "Main #13" },
  { date: "2026-09-04", type: "TRANSFER", player: "Soumen Shoummo", squad: "Main #2" },
  { date: "2026-08-31", type: "TRANSFER", player: "Badhan Barua", squad: "Main #21" },
  { date: "2026-08-10", type: "TRANSFER", player: "Suraj Chowdhury", squad: "Main #20" },
  { date: "2026-08-08", type: "TRANSFER", player: "Niloy barua", squad: "Main #18" },
  { date: "2026-08-08", type: "TRANSFER", player: "Supan Barua", squad: "Main #17" },
  { date: "2026-08-07", type: "TRANSFER", player: "Raef Fear", squad: "Main #16" },
  { date: "2026-08-05", type: "TRANSFER", player: "Swapnil Raj", squad: "Main #15" },
  { date: "2026-08-05", type: "TRANSFER", player: "Ayon Barua", squad: "Main #14" },
  { date: "2026-08-05", type: "TRANSFER", player: "Dhruba Barua", squad: "Main #13" },
  { date: "2026-08-04", type: "TRANSFER", player: "Srabon Barua", squad: "Main #8", fromClub: "Royal revengers Bashundhara" },
  { date: "2026-08-04", type: "TRANSFER", player: "Arko Barua", squad: "Main #5" },
  { date: "2026-05-31", type: "TRANSFER", player: "Ananta Barua", squad: "Main #19" },
  { date: "2026-05-31", type: "TRANSFER", player: "Oishik Barua", squad: "Main #28" },
  { date: "2026-05-31", type: "TRANSFER", player: "Arnab Barua", squad: "Main #12" },
  { date: "2026-05-30", type: "TRANSFER", player: "Aditya Barua.", squad: "Main #5" },
  { date: "2026-05-30", type: "NEW_REGISTER", player: "সৌ রভ", squad: "Main #9" },
  { date: "2026-05-30", type: "NEW_REGISTER", player: "Pushan Barua", squad: "Main #4" },
  { date: "2026-05-30", type: "NEW_REGISTER", player: "Pranta Priyo", squad: "Main #3" },
  { date: "2026-05-27", type: "TRANSFER", player: "Sonjoy Barua Shanto", squad: "Main #8", fromClub: "Nirbana United Efc" },
  { date: "2026-05-27", type: "UNREGISTER", player: "Sonjoy Barua Shanto", squad: "Main #8" },
  { date: "2026-05-25", type: "TRANSFER", player: "Sonjoy Barua Shanto", squad: "Main #8" },
  { date: "2026-05-25", type: "NEW_REGISTER", player: "Arnob Barua", squad: "Main #30" },
  { date: "2026-05-25", type: "TRANSFER", player: "Joy Barua Kawshik", squad: "Main #7" },
  { date: "2026-05-25", type: "TRANSFER", player: "Piyas Barua", squad: "Main #9" },
  { date: "2026-05-25", type: "TRANSFER", player: "ontu barua", squad: "Main #11" },
  { date: "2026-05-25", type: "TRANSFER", player: "Niloy Barua", squad: "Main #10" },
];

export type ClubRankingSnapshot = {
  scope: string; // e.g. "All-Time", "eFootball 2026"
  position: number;
  division: string;
  rating: number;
  played: number;
  wins: number;
  draws: number;
  goalsFor: number;
  goalsAgainst: number;
  winPct: number;
};

// Straight from the tracker's Rankings tab. Note: this is a periodic
// snapshot the tracker recalculates — it can lag the club's live match log
// (the Matches page) by a game or two right after a new match is played.
export const CLUB_RANKINGS: ClubRankingSnapshot[] = [
  { scope: "All-Time", position: 112, division: "FOUNDATION", rating: 964.03, played: 13, wins: 1, draws: 0, goalsFor: 32, goalsAgainst: 108, winPct: 7.7 },
  { scope: "eFootball 2027", position: 94, division: "FOUNDATION", rating: 984.49, played: 8, wins: 1, draws: 0, goalsFor: 18, goalsAgainst: 65, winPct: 12.5 },
  { scope: "eFootball 2026", position: 68, division: "FOUNDATION", rating: 974.42, played: 5, wins: 0, draws: 0, goalsFor: 14, goalsAgainst: 43, winPct: 0 },
];
